version: "3.9"
services:
  server:
    container_name: larik-server
    image: nginx
    ports:
      - '80:80'
    volumes:
      - "./etc/nginx:/etc/nginx"
      - './public:/var/www/html/public'
  app:
    container_name: larik-app
    # image: php:8.2.12-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/var/www/html'